### ISSUE TITLE
common.json requested by SoulBot upon interaction ping. 

### ISSUE THREAD

**Issue by Novel-Idea** [ktrzonkowski/soulbot#4]
Reproduction Steps:
1. Start Bot with console.log('hello world') enabled in Message Section
2. Run node soulbot.js
3. Ping soulbot with an @ in the test server. 
4. ---> Will respond with error about unable to locate "common.json." 

```
C:\Users\Administrator\Documents\GitHub\node_modules\chance\chance.js:421
          throw new RangeError("Chance: Cannot pickone() from an empty array");
          ^

RangeError: Chance: Cannot pickone() from an empty array
    at Chance.pickone (C:\Users\Administrator\Documents\GitHub\node_modules\chance\chance.js:421:17)
    at Object.basicResponse (C:\Users\Administrator\Documents\GitHub\helpers\common.js:29:37)
    at Client.<anonymous> (C:\Users\Administrator\Documents\GitHub\soulbot.js:175:27)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at MessageCreateHandler.handle (C:\Users\Administrator\Documents\GitHub\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Administrator\Documents\GitHub\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Administrator\Documents\GitHub\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (C:\Users\Administrator\Documents\GitHub\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:293:17)
    at WebSocket.onMessage (C:\Users\Administrator\Documents\GitHub\node_modules\ws\lib\EventTarget.js:99:16)

C:\Users\Administrator\Documents\GitHub>
```

**Comment by ktrzonkowski** [comment]
This should be fixed now; the basicResponse function in common.js now gives a default response if the responseList array is empty.
